/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IMHCalendarEvent, IMHCalendarFullOptions, UserApi } from "./types";
import { DragDropState } from "./utils/DragDropHandler";
import { MHCalendarViewType } from "./store/mh-calendar-store.types";
import { IMHCalendarPopoverAlignment, IMHCalendarPopoverAnchorRect } from "./utils/PopoverPositionUtils";
export { IMHCalendarEvent, IMHCalendarFullOptions, UserApi } from "./types";
export { DragDropState } from "./utils/DragDropHandler";
export { MHCalendarViewType } from "./store/mh-calendar-store.types";
export { IMHCalendarPopoverAlignment, IMHCalendarPopoverAnchorRect } from "./utils/PopoverPositionUtils";
export namespace Components {
    interface MhCalendar {
        /**
          * @default {}
         */
        "config": IMHCalendarFullOptions;
        /**
          * @default []
         */
        "events": IMHCalendarEvent[];
        "getApi": () => Promise<UserApi>;
    }
    interface MhCalendarAgendaView {
    }
    interface MhCalendarDay {
        "day"?: Date;
        /**
          * @default false
         */
        "showCurrentDate": boolean;
    }
    interface MhCalendarDayAllDayEventsHolder {
        "allDayEvents": IMHCalendarEvent[];
        "dragDropState": DragDropState;
        "handleDragLeave": (e: DragEvent) => void;
        "handleDragOver": (e: DragEvent) => void;
        "handleDrop": (e: DragEvent) => void;
        "showCurrentDate": boolean;
    }
    interface MhCalendarDayDraggedEventPreview {
        "calendarDayElementHeight"?: number;
        "day"?: Date;
        "dragDropState": DragDropState;
        "viewType"?: MHCalendarViewType;
    }
    interface MhCalendarDayMonthViewEvents {
        "calendarDayElementHeight"?: number;
        "day"?: Date;
        "dragDropState"?: DragDropState;
        "groupedEvents": IMHCalendarEvent[];
        "maxVisibleEventsInMonthView": number;
    }
    interface MhCalendarDayTimeViewEvents {
        "calendarDayElementHeight"?: number;
        "day"?: Date;
        "groupedEvents": Map<string, IMHCalendarEvent[]>;
    }
    interface MhCalendarDayTimeViewOverlays {
        "calendarDayElementHeight": number;
        "currentTimePosition"?: { top: string };
        "day": Date;
        "isTimeView": boolean;
        "isToday": boolean;
    }
    interface MhCalendarEvent {
        "dayHeight"?: number;
        "dayOfRendering"?: Date;
        "event"?: IMHCalendarEvent;
        "eventTopPosition"?: number;
        "instanceOfEvent"?: string;
        /**
          * @default false
         */
        "isDragged": boolean;
    }
    interface MhCalendarEventForm {
        "event": IMHCalendarEvent;
        /**
          * @default false
         */
        "isNewEvent": boolean;
    }
    interface MhCalendarEventFull {
        "event"?: IMHCalendarEvent;
        "resizePreviewEndDate"?: Date | null;
    }
    /**
     * A day/cell's overflowed events shown in a backdrop-less popover — a header
     * with the date and the full event list. Anchored next to `anchorRect` and
     * dismissible via outside click / Escape.
     * Renders its own popover chrome directly (no separate slotted custom
     * element) so the event list stays reactive: a slot host that doesn't get
     * its own prop changes can fail to re-relocate updated slotted content in
     * non-shadow Stencil components.
     */
    interface MhCalendarEventListPopup {
        /**
          * @default 'bottom'
         */
        "alignment": IMHCalendarPopoverAlignment;
        "anchorRect": IMHCalendarPopoverAnchorRect;
        "date": Date;
        /**
          * @default []
         */
        "events": IMHCalendarEvent[];
    }
    interface MhCalendarEventSmall {
        "event"?: IMHCalendarEvent;
    }
    interface MhCalendarHeader {
        /**
          * @default false
         */
        "showCurrentDate": boolean;
    }
    interface MhCalendarModal {
    }
    interface MhCalendarMonth {
    }
    interface MhCalendarMoreEventsIndicator {
        "hiddenCount": number;
    }
    interface MhCalendarMultiView {
    }
    interface MhCalendarNavigation {
    }
    interface MhCalendarResizeEventHandler {
        /**
          * @default null
         */
        "dayOfRendering": null | Date;
        "eventColor"?: string;
        /**
          * @default null
         */
        "eventEndDate": null | Date;
        "eventHeight": string;
        "eventId": string;
        /**
          * @default null
         */
        "eventStartDate": null | Date;
    }
    interface MhCalendarResourceView {
    }
    interface MhCalendarTimeSlots {
    }
    interface MhViewSwitcher {
    }
}
export interface MhCalendarEventFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMhCalendarEventFormElement;
}
export interface MhCalendarEventListPopupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMhCalendarEventListPopupElement;
}
export interface MhCalendarMoreEventsIndicatorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMhCalendarMoreEventsIndicatorElement;
}
export interface MhCalendarResizeEventHandlerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMhCalendarResizeEventHandlerElement;
}
declare global {
    interface HTMLMhCalendarElement extends Components.MhCalendar, HTMLStencilElement {
    }
    var HTMLMhCalendarElement: {
        prototype: HTMLMhCalendarElement;
        new (): HTMLMhCalendarElement;
    };
    interface HTMLMhCalendarAgendaViewElement extends Components.MhCalendarAgendaView, HTMLStencilElement {
    }
    var HTMLMhCalendarAgendaViewElement: {
        prototype: HTMLMhCalendarAgendaViewElement;
        new (): HTMLMhCalendarAgendaViewElement;
    };
    interface HTMLMhCalendarDayElement extends Components.MhCalendarDay, HTMLStencilElement {
    }
    var HTMLMhCalendarDayElement: {
        prototype: HTMLMhCalendarDayElement;
        new (): HTMLMhCalendarDayElement;
    };
    interface HTMLMhCalendarDayAllDayEventsHolderElement extends Components.MhCalendarDayAllDayEventsHolder, HTMLStencilElement {
    }
    var HTMLMhCalendarDayAllDayEventsHolderElement: {
        prototype: HTMLMhCalendarDayAllDayEventsHolderElement;
        new (): HTMLMhCalendarDayAllDayEventsHolderElement;
    };
    interface HTMLMhCalendarDayDraggedEventPreviewElement extends Components.MhCalendarDayDraggedEventPreview, HTMLStencilElement {
    }
    var HTMLMhCalendarDayDraggedEventPreviewElement: {
        prototype: HTMLMhCalendarDayDraggedEventPreviewElement;
        new (): HTMLMhCalendarDayDraggedEventPreviewElement;
    };
    interface HTMLMhCalendarDayMonthViewEventsElement extends Components.MhCalendarDayMonthViewEvents, HTMLStencilElement {
    }
    var HTMLMhCalendarDayMonthViewEventsElement: {
        prototype: HTMLMhCalendarDayMonthViewEventsElement;
        new (): HTMLMhCalendarDayMonthViewEventsElement;
    };
    interface HTMLMhCalendarDayTimeViewEventsElement extends Components.MhCalendarDayTimeViewEvents, HTMLStencilElement {
    }
    var HTMLMhCalendarDayTimeViewEventsElement: {
        prototype: HTMLMhCalendarDayTimeViewEventsElement;
        new (): HTMLMhCalendarDayTimeViewEventsElement;
    };
    interface HTMLMhCalendarDayTimeViewOverlaysElement extends Components.MhCalendarDayTimeViewOverlays, HTMLStencilElement {
    }
    var HTMLMhCalendarDayTimeViewOverlaysElement: {
        prototype: HTMLMhCalendarDayTimeViewOverlaysElement;
        new (): HTMLMhCalendarDayTimeViewOverlaysElement;
    };
    interface HTMLMhCalendarEventElement extends Components.MhCalendarEvent, HTMLStencilElement {
    }
    var HTMLMhCalendarEventElement: {
        prototype: HTMLMhCalendarEventElement;
        new (): HTMLMhCalendarEventElement;
    };
    interface HTMLMhCalendarEventFormElementEventMap {
        "save": IMHCalendarEvent;
        "cancel": void;
    }
    interface HTMLMhCalendarEventFormElement extends Components.MhCalendarEventForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMhCalendarEventFormElementEventMap>(type: K, listener: (this: HTMLMhCalendarEventFormElement, ev: MhCalendarEventFormCustomEvent<HTMLMhCalendarEventFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMhCalendarEventFormElementEventMap>(type: K, listener: (this: HTMLMhCalendarEventFormElement, ev: MhCalendarEventFormCustomEvent<HTMLMhCalendarEventFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMhCalendarEventFormElement: {
        prototype: HTMLMhCalendarEventFormElement;
        new (): HTMLMhCalendarEventFormElement;
    };
    interface HTMLMhCalendarEventFullElement extends Components.MhCalendarEventFull, HTMLStencilElement {
    }
    var HTMLMhCalendarEventFullElement: {
        prototype: HTMLMhCalendarEventFullElement;
        new (): HTMLMhCalendarEventFullElement;
    };
    interface HTMLMhCalendarEventListPopupElementEventMap {
        "closePopover": void;
    }
    /**
     * A day/cell's overflowed events shown in a backdrop-less popover — a header
     * with the date and the full event list. Anchored next to `anchorRect` and
     * dismissible via outside click / Escape.
     * Renders its own popover chrome directly (no separate slotted custom
     * element) so the event list stays reactive: a slot host that doesn't get
     * its own prop changes can fail to re-relocate updated slotted content in
     * non-shadow Stencil components.
     */
    interface HTMLMhCalendarEventListPopupElement extends Components.MhCalendarEventListPopup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMhCalendarEventListPopupElementEventMap>(type: K, listener: (this: HTMLMhCalendarEventListPopupElement, ev: MhCalendarEventListPopupCustomEvent<HTMLMhCalendarEventListPopupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMhCalendarEventListPopupElementEventMap>(type: K, listener: (this: HTMLMhCalendarEventListPopupElement, ev: MhCalendarEventListPopupCustomEvent<HTMLMhCalendarEventListPopupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMhCalendarEventListPopupElement: {
        prototype: HTMLMhCalendarEventListPopupElement;
        new (): HTMLMhCalendarEventListPopupElement;
    };
    interface HTMLMhCalendarEventSmallElement extends Components.MhCalendarEventSmall, HTMLStencilElement {
    }
    var HTMLMhCalendarEventSmallElement: {
        prototype: HTMLMhCalendarEventSmallElement;
        new (): HTMLMhCalendarEventSmallElement;
    };
    interface HTMLMhCalendarHeaderElement extends Components.MhCalendarHeader, HTMLStencilElement {
    }
    var HTMLMhCalendarHeaderElement: {
        prototype: HTMLMhCalendarHeaderElement;
        new (): HTMLMhCalendarHeaderElement;
    };
    interface HTMLMhCalendarModalElement extends Components.MhCalendarModal, HTMLStencilElement {
    }
    var HTMLMhCalendarModalElement: {
        prototype: HTMLMhCalendarModalElement;
        new (): HTMLMhCalendarModalElement;
    };
    interface HTMLMhCalendarMonthElement extends Components.MhCalendarMonth, HTMLStencilElement {
    }
    var HTMLMhCalendarMonthElement: {
        prototype: HTMLMhCalendarMonthElement;
        new (): HTMLMhCalendarMonthElement;
    };
    interface HTMLMhCalendarMoreEventsIndicatorElementEventMap {
        "moreClick": MouseEvent;
    }
    interface HTMLMhCalendarMoreEventsIndicatorElement extends Components.MhCalendarMoreEventsIndicator, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMhCalendarMoreEventsIndicatorElementEventMap>(type: K, listener: (this: HTMLMhCalendarMoreEventsIndicatorElement, ev: MhCalendarMoreEventsIndicatorCustomEvent<HTMLMhCalendarMoreEventsIndicatorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMhCalendarMoreEventsIndicatorElementEventMap>(type: K, listener: (this: HTMLMhCalendarMoreEventsIndicatorElement, ev: MhCalendarMoreEventsIndicatorCustomEvent<HTMLMhCalendarMoreEventsIndicatorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMhCalendarMoreEventsIndicatorElement: {
        prototype: HTMLMhCalendarMoreEventsIndicatorElement;
        new (): HTMLMhCalendarMoreEventsIndicatorElement;
    };
    interface HTMLMhCalendarMultiViewElement extends Components.MhCalendarMultiView, HTMLStencilElement {
    }
    var HTMLMhCalendarMultiViewElement: {
        prototype: HTMLMhCalendarMultiViewElement;
        new (): HTMLMhCalendarMultiViewElement;
    };
    interface HTMLMhCalendarNavigationElement extends Components.MhCalendarNavigation, HTMLStencilElement {
    }
    var HTMLMhCalendarNavigationElement: {
        prototype: HTMLMhCalendarNavigationElement;
        new (): HTMLMhCalendarNavigationElement;
    };
    interface HTMLMhCalendarResizeEventHandlerElementEventMap {
        "resizePreview": Date | null;
    }
    interface HTMLMhCalendarResizeEventHandlerElement extends Components.MhCalendarResizeEventHandler, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMhCalendarResizeEventHandlerElementEventMap>(type: K, listener: (this: HTMLMhCalendarResizeEventHandlerElement, ev: MhCalendarResizeEventHandlerCustomEvent<HTMLMhCalendarResizeEventHandlerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMhCalendarResizeEventHandlerElementEventMap>(type: K, listener: (this: HTMLMhCalendarResizeEventHandlerElement, ev: MhCalendarResizeEventHandlerCustomEvent<HTMLMhCalendarResizeEventHandlerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMhCalendarResizeEventHandlerElement: {
        prototype: HTMLMhCalendarResizeEventHandlerElement;
        new (): HTMLMhCalendarResizeEventHandlerElement;
    };
    interface HTMLMhCalendarResourceViewElement extends Components.MhCalendarResourceView, HTMLStencilElement {
    }
    var HTMLMhCalendarResourceViewElement: {
        prototype: HTMLMhCalendarResourceViewElement;
        new (): HTMLMhCalendarResourceViewElement;
    };
    interface HTMLMhCalendarTimeSlotsElement extends Components.MhCalendarTimeSlots, HTMLStencilElement {
    }
    var HTMLMhCalendarTimeSlotsElement: {
        prototype: HTMLMhCalendarTimeSlotsElement;
        new (): HTMLMhCalendarTimeSlotsElement;
    };
    interface HTMLMhViewSwitcherElement extends Components.MhViewSwitcher, HTMLStencilElement {
    }
    var HTMLMhViewSwitcherElement: {
        prototype: HTMLMhViewSwitcherElement;
        new (): HTMLMhViewSwitcherElement;
    };
    interface HTMLElementTagNameMap {
        "mh-calendar": HTMLMhCalendarElement;
        "mh-calendar-agenda-view": HTMLMhCalendarAgendaViewElement;
        "mh-calendar-day": HTMLMhCalendarDayElement;
        "mh-calendar-day-all-day-events-holder": HTMLMhCalendarDayAllDayEventsHolderElement;
        "mh-calendar-day-dragged-event-preview": HTMLMhCalendarDayDraggedEventPreviewElement;
        "mh-calendar-day-month-view-events": HTMLMhCalendarDayMonthViewEventsElement;
        "mh-calendar-day-time-view-events": HTMLMhCalendarDayTimeViewEventsElement;
        "mh-calendar-day-time-view-overlays": HTMLMhCalendarDayTimeViewOverlaysElement;
        "mh-calendar-event": HTMLMhCalendarEventElement;
        "mh-calendar-event-form": HTMLMhCalendarEventFormElement;
        "mh-calendar-event-full": HTMLMhCalendarEventFullElement;
        "mh-calendar-event-list-popup": HTMLMhCalendarEventListPopupElement;
        "mh-calendar-event-small": HTMLMhCalendarEventSmallElement;
        "mh-calendar-header": HTMLMhCalendarHeaderElement;
        "mh-calendar-modal": HTMLMhCalendarModalElement;
        "mh-calendar-month": HTMLMhCalendarMonthElement;
        "mh-calendar-more-events-indicator": HTMLMhCalendarMoreEventsIndicatorElement;
        "mh-calendar-multi-view": HTMLMhCalendarMultiViewElement;
        "mh-calendar-navigation": HTMLMhCalendarNavigationElement;
        "mh-calendar-resize-event-handler": HTMLMhCalendarResizeEventHandlerElement;
        "mh-calendar-resource-view": HTMLMhCalendarResourceViewElement;
        "mh-calendar-time-slots": HTMLMhCalendarTimeSlotsElement;
        "mh-view-switcher": HTMLMhViewSwitcherElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface MhCalendar {
        /**
          * @default {}
         */
        "config"?: IMHCalendarFullOptions;
        /**
          * @default []
         */
        "events"?: IMHCalendarEvent[];
    }
    interface MhCalendarAgendaView {
    }
    interface MhCalendarDay {
        "day"?: Date;
        /**
          * @default false
         */
        "showCurrentDate"?: boolean;
    }
    interface MhCalendarDayAllDayEventsHolder {
        "allDayEvents": IMHCalendarEvent[];
        "dragDropState": DragDropState;
        "handleDragLeave": (e: DragEvent) => void;
        "handleDragOver": (e: DragEvent) => void;
        "handleDrop": (e: DragEvent) => void;
        "showCurrentDate": boolean;
    }
    interface MhCalendarDayDraggedEventPreview {
        "calendarDayElementHeight"?: number;
        "day"?: Date;
        "dragDropState": DragDropState;
        "viewType"?: MHCalendarViewType;
    }
    interface MhCalendarDayMonthViewEvents {
        "calendarDayElementHeight"?: number;
        "day"?: Date;
        "dragDropState"?: DragDropState;
        "groupedEvents": IMHCalendarEvent[];
        "maxVisibleEventsInMonthView": number;
    }
    interface MhCalendarDayTimeViewEvents {
        "calendarDayElementHeight"?: number;
        "day"?: Date;
        "groupedEvents": Map<string, IMHCalendarEvent[]>;
    }
    interface MhCalendarDayTimeViewOverlays {
        "calendarDayElementHeight": number;
        "currentTimePosition"?: { top: string };
        "day": Date;
        "isTimeView": boolean;
        "isToday": boolean;
    }
    interface MhCalendarEvent {
        "dayHeight"?: number;
        "dayOfRendering"?: Date;
        "event"?: IMHCalendarEvent;
        "eventTopPosition"?: number;
        "instanceOfEvent"?: string;
        /**
          * @default false
         */
        "isDragged"?: boolean;
    }
    interface MhCalendarEventForm {
        "event": IMHCalendarEvent;
        /**
          * @default false
         */
        "isNewEvent"?: boolean;
        "onCancel"?: (event: MhCalendarEventFormCustomEvent<void>) => void;
        "onSave"?: (event: MhCalendarEventFormCustomEvent<IMHCalendarEvent>) => void;
    }
    interface MhCalendarEventFull {
        "event"?: IMHCalendarEvent;
        "resizePreviewEndDate"?: Date | null;
    }
    /**
     * A day/cell's overflowed events shown in a backdrop-less popover — a header
     * with the date and the full event list. Anchored next to `anchorRect` and
     * dismissible via outside click / Escape.
     * Renders its own popover chrome directly (no separate slotted custom
     * element) so the event list stays reactive: a slot host that doesn't get
     * its own prop changes can fail to re-relocate updated slotted content in
     * non-shadow Stencil components.
     */
    interface MhCalendarEventListPopup {
        /**
          * @default 'bottom'
         */
        "alignment"?: IMHCalendarPopoverAlignment;
        "anchorRect": IMHCalendarPopoverAnchorRect;
        "date": Date;
        /**
          * @default []
         */
        "events"?: IMHCalendarEvent[];
        "onClosePopover"?: (event: MhCalendarEventListPopupCustomEvent<void>) => void;
    }
    interface MhCalendarEventSmall {
        "event"?: IMHCalendarEvent;
    }
    interface MhCalendarHeader {
        /**
          * @default false
         */
        "showCurrentDate"?: boolean;
    }
    interface MhCalendarModal {
    }
    interface MhCalendarMonth {
    }
    interface MhCalendarMoreEventsIndicator {
        "hiddenCount": number;
        "onMoreClick"?: (event: MhCalendarMoreEventsIndicatorCustomEvent<MouseEvent>) => void;
    }
    interface MhCalendarMultiView {
    }
    interface MhCalendarNavigation {
    }
    interface MhCalendarResizeEventHandler {
        /**
          * @default null
         */
        "dayOfRendering"?: null | Date;
        "eventColor"?: string;
        /**
          * @default null
         */
        "eventEndDate"?: null | Date;
        "eventHeight": string;
        "eventId": string;
        /**
          * @default null
         */
        "eventStartDate"?: null | Date;
        "onResizePreview"?: (event: MhCalendarResizeEventHandlerCustomEvent<Date | null>) => void;
    }
    interface MhCalendarResourceView {
    }
    interface MhCalendarTimeSlots {
    }
    interface MhViewSwitcher {
    }

    interface MhCalendarDayAttributes {
        "showCurrentDate": boolean;
    }
    interface MhCalendarDayAllDayEventsHolderAttributes {
        "showCurrentDate": boolean;
    }
    interface MhCalendarDayDraggedEventPreviewAttributes {
        "calendarDayElementHeight": number;
        "viewType": MHCalendarViewType;
    }
    interface MhCalendarDayMonthViewEventsAttributes {
        "maxVisibleEventsInMonthView": number;
        "calendarDayElementHeight": number;
    }
    interface MhCalendarDayTimeViewEventsAttributes {
        "calendarDayElementHeight": number;
    }
    interface MhCalendarDayTimeViewOverlaysAttributes {
        "calendarDayElementHeight": number;
        "isToday": boolean;
        "isTimeView": boolean;
    }
    interface MhCalendarEventAttributes {
        "dayHeight": number;
        "eventTopPosition": number;
        "isDragged": boolean;
        "instanceOfEvent": string;
    }
    interface MhCalendarEventFormAttributes {
        "isNewEvent": boolean;
    }
    interface MhCalendarEventListPopupAttributes {
        "alignment": IMHCalendarPopoverAlignment;
    }
    interface MhCalendarHeaderAttributes {
        "showCurrentDate": boolean;
    }
    interface MhCalendarMoreEventsIndicatorAttributes {
        "hiddenCount": number;
    }
    interface MhCalendarResizeEventHandlerAttributes {
        "eventId": string;
        "eventHeight": string;
        "eventColor": string;
    }

    interface IntrinsicElements {
        "mh-calendar": MhCalendar;
        "mh-calendar-agenda-view": MhCalendarAgendaView;
        "mh-calendar-day": Omit<MhCalendarDay, keyof MhCalendarDayAttributes> & { [K in keyof MhCalendarDay & keyof MhCalendarDayAttributes]?: MhCalendarDay[K] } & { [K in keyof MhCalendarDay & keyof MhCalendarDayAttributes as `attr:${K}`]?: MhCalendarDayAttributes[K] } & { [K in keyof MhCalendarDay & keyof MhCalendarDayAttributes as `prop:${K}`]?: MhCalendarDay[K] };
        "mh-calendar-day-all-day-events-holder": Omit<MhCalendarDayAllDayEventsHolder, keyof MhCalendarDayAllDayEventsHolderAttributes> & { [K in keyof MhCalendarDayAllDayEventsHolder & keyof MhCalendarDayAllDayEventsHolderAttributes]?: MhCalendarDayAllDayEventsHolder[K] } & { [K in keyof MhCalendarDayAllDayEventsHolder & keyof MhCalendarDayAllDayEventsHolderAttributes as `attr:${K}`]?: MhCalendarDayAllDayEventsHolderAttributes[K] } & { [K in keyof MhCalendarDayAllDayEventsHolder & keyof MhCalendarDayAllDayEventsHolderAttributes as `prop:${K}`]?: MhCalendarDayAllDayEventsHolder[K] } & OneOf<"showCurrentDate", MhCalendarDayAllDayEventsHolder["showCurrentDate"], MhCalendarDayAllDayEventsHolderAttributes["showCurrentDate"]>;
        "mh-calendar-day-dragged-event-preview": Omit<MhCalendarDayDraggedEventPreview, keyof MhCalendarDayDraggedEventPreviewAttributes> & { [K in keyof MhCalendarDayDraggedEventPreview & keyof MhCalendarDayDraggedEventPreviewAttributes]?: MhCalendarDayDraggedEventPreview[K] } & { [K in keyof MhCalendarDayDraggedEventPreview & keyof MhCalendarDayDraggedEventPreviewAttributes as `attr:${K}`]?: MhCalendarDayDraggedEventPreviewAttributes[K] } & { [K in keyof MhCalendarDayDraggedEventPreview & keyof MhCalendarDayDraggedEventPreviewAttributes as `prop:${K}`]?: MhCalendarDayDraggedEventPreview[K] };
        "mh-calendar-day-month-view-events": Omit<MhCalendarDayMonthViewEvents, keyof MhCalendarDayMonthViewEventsAttributes> & { [K in keyof MhCalendarDayMonthViewEvents & keyof MhCalendarDayMonthViewEventsAttributes]?: MhCalendarDayMonthViewEvents[K] } & { [K in keyof MhCalendarDayMonthViewEvents & keyof MhCalendarDayMonthViewEventsAttributes as `attr:${K}`]?: MhCalendarDayMonthViewEventsAttributes[K] } & { [K in keyof MhCalendarDayMonthViewEvents & keyof MhCalendarDayMonthViewEventsAttributes as `prop:${K}`]?: MhCalendarDayMonthViewEvents[K] } & OneOf<"maxVisibleEventsInMonthView", MhCalendarDayMonthViewEvents["maxVisibleEventsInMonthView"], MhCalendarDayMonthViewEventsAttributes["maxVisibleEventsInMonthView"]>;
        "mh-calendar-day-time-view-events": Omit<MhCalendarDayTimeViewEvents, keyof MhCalendarDayTimeViewEventsAttributes> & { [K in keyof MhCalendarDayTimeViewEvents & keyof MhCalendarDayTimeViewEventsAttributes]?: MhCalendarDayTimeViewEvents[K] } & { [K in keyof MhCalendarDayTimeViewEvents & keyof MhCalendarDayTimeViewEventsAttributes as `attr:${K}`]?: MhCalendarDayTimeViewEventsAttributes[K] } & { [K in keyof MhCalendarDayTimeViewEvents & keyof MhCalendarDayTimeViewEventsAttributes as `prop:${K}`]?: MhCalendarDayTimeViewEvents[K] };
        "mh-calendar-day-time-view-overlays": Omit<MhCalendarDayTimeViewOverlays, keyof MhCalendarDayTimeViewOverlaysAttributes> & { [K in keyof MhCalendarDayTimeViewOverlays & keyof MhCalendarDayTimeViewOverlaysAttributes]?: MhCalendarDayTimeViewOverlays[K] } & { [K in keyof MhCalendarDayTimeViewOverlays & keyof MhCalendarDayTimeViewOverlaysAttributes as `attr:${K}`]?: MhCalendarDayTimeViewOverlaysAttributes[K] } & { [K in keyof MhCalendarDayTimeViewOverlays & keyof MhCalendarDayTimeViewOverlaysAttributes as `prop:${K}`]?: MhCalendarDayTimeViewOverlays[K] } & OneOf<"calendarDayElementHeight", MhCalendarDayTimeViewOverlays["calendarDayElementHeight"], MhCalendarDayTimeViewOverlaysAttributes["calendarDayElementHeight"]> & OneOf<"isToday", MhCalendarDayTimeViewOverlays["isToday"], MhCalendarDayTimeViewOverlaysAttributes["isToday"]> & OneOf<"isTimeView", MhCalendarDayTimeViewOverlays["isTimeView"], MhCalendarDayTimeViewOverlaysAttributes["isTimeView"]>;
        "mh-calendar-event": Omit<MhCalendarEvent, keyof MhCalendarEventAttributes> & { [K in keyof MhCalendarEvent & keyof MhCalendarEventAttributes]?: MhCalendarEvent[K] } & { [K in keyof MhCalendarEvent & keyof MhCalendarEventAttributes as `attr:${K}`]?: MhCalendarEventAttributes[K] } & { [K in keyof MhCalendarEvent & keyof MhCalendarEventAttributes as `prop:${K}`]?: MhCalendarEvent[K] };
        "mh-calendar-event-form": Omit<MhCalendarEventForm, keyof MhCalendarEventFormAttributes> & { [K in keyof MhCalendarEventForm & keyof MhCalendarEventFormAttributes]?: MhCalendarEventForm[K] } & { [K in keyof MhCalendarEventForm & keyof MhCalendarEventFormAttributes as `attr:${K}`]?: MhCalendarEventFormAttributes[K] } & { [K in keyof MhCalendarEventForm & keyof MhCalendarEventFormAttributes as `prop:${K}`]?: MhCalendarEventForm[K] };
        "mh-calendar-event-full": MhCalendarEventFull;
        "mh-calendar-event-list-popup": Omit<MhCalendarEventListPopup, keyof MhCalendarEventListPopupAttributes> & { [K in keyof MhCalendarEventListPopup & keyof MhCalendarEventListPopupAttributes]?: MhCalendarEventListPopup[K] } & { [K in keyof MhCalendarEventListPopup & keyof MhCalendarEventListPopupAttributes as `attr:${K}`]?: MhCalendarEventListPopupAttributes[K] } & { [K in keyof MhCalendarEventListPopup & keyof MhCalendarEventListPopupAttributes as `prop:${K}`]?: MhCalendarEventListPopup[K] };
        "mh-calendar-event-small": MhCalendarEventSmall;
        "mh-calendar-header": Omit<MhCalendarHeader, keyof MhCalendarHeaderAttributes> & { [K in keyof MhCalendarHeader & keyof MhCalendarHeaderAttributes]?: MhCalendarHeader[K] } & { [K in keyof MhCalendarHeader & keyof MhCalendarHeaderAttributes as `attr:${K}`]?: MhCalendarHeaderAttributes[K] } & { [K in keyof MhCalendarHeader & keyof MhCalendarHeaderAttributes as `prop:${K}`]?: MhCalendarHeader[K] };
        "mh-calendar-modal": MhCalendarModal;
        "mh-calendar-month": MhCalendarMonth;
        "mh-calendar-more-events-indicator": Omit<MhCalendarMoreEventsIndicator, keyof MhCalendarMoreEventsIndicatorAttributes> & { [K in keyof MhCalendarMoreEventsIndicator & keyof MhCalendarMoreEventsIndicatorAttributes]?: MhCalendarMoreEventsIndicator[K] } & { [K in keyof MhCalendarMoreEventsIndicator & keyof MhCalendarMoreEventsIndicatorAttributes as `attr:${K}`]?: MhCalendarMoreEventsIndicatorAttributes[K] } & { [K in keyof MhCalendarMoreEventsIndicator & keyof MhCalendarMoreEventsIndicatorAttributes as `prop:${K}`]?: MhCalendarMoreEventsIndicator[K] } & OneOf<"hiddenCount", MhCalendarMoreEventsIndicator["hiddenCount"], MhCalendarMoreEventsIndicatorAttributes["hiddenCount"]>;
        "mh-calendar-multi-view": MhCalendarMultiView;
        "mh-calendar-navigation": MhCalendarNavigation;
        "mh-calendar-resize-event-handler": Omit<MhCalendarResizeEventHandler, keyof MhCalendarResizeEventHandlerAttributes> & { [K in keyof MhCalendarResizeEventHandler & keyof MhCalendarResizeEventHandlerAttributes]?: MhCalendarResizeEventHandler[K] } & { [K in keyof MhCalendarResizeEventHandler & keyof MhCalendarResizeEventHandlerAttributes as `attr:${K}`]?: MhCalendarResizeEventHandlerAttributes[K] } & { [K in keyof MhCalendarResizeEventHandler & keyof MhCalendarResizeEventHandlerAttributes as `prop:${K}`]?: MhCalendarResizeEventHandler[K] } & OneOf<"eventId", MhCalendarResizeEventHandler["eventId"], MhCalendarResizeEventHandlerAttributes["eventId"]> & OneOf<"eventHeight", MhCalendarResizeEventHandler["eventHeight"], MhCalendarResizeEventHandlerAttributes["eventHeight"]>;
        "mh-calendar-resource-view": MhCalendarResourceView;
        "mh-calendar-time-slots": MhCalendarTimeSlots;
        "mh-view-switcher": MhViewSwitcher;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mh-calendar": LocalJSX.IntrinsicElements["mh-calendar"] & JSXBase.HTMLAttributes<HTMLMhCalendarElement>;
            "mh-calendar-agenda-view": LocalJSX.IntrinsicElements["mh-calendar-agenda-view"] & JSXBase.HTMLAttributes<HTMLMhCalendarAgendaViewElement>;
            "mh-calendar-day": LocalJSX.IntrinsicElements["mh-calendar-day"] & JSXBase.HTMLAttributes<HTMLMhCalendarDayElement>;
            "mh-calendar-day-all-day-events-holder": LocalJSX.IntrinsicElements["mh-calendar-day-all-day-events-holder"] & JSXBase.HTMLAttributes<HTMLMhCalendarDayAllDayEventsHolderElement>;
            "mh-calendar-day-dragged-event-preview": LocalJSX.IntrinsicElements["mh-calendar-day-dragged-event-preview"] & JSXBase.HTMLAttributes<HTMLMhCalendarDayDraggedEventPreviewElement>;
            "mh-calendar-day-month-view-events": LocalJSX.IntrinsicElements["mh-calendar-day-month-view-events"] & JSXBase.HTMLAttributes<HTMLMhCalendarDayMonthViewEventsElement>;
            "mh-calendar-day-time-view-events": LocalJSX.IntrinsicElements["mh-calendar-day-time-view-events"] & JSXBase.HTMLAttributes<HTMLMhCalendarDayTimeViewEventsElement>;
            "mh-calendar-day-time-view-overlays": LocalJSX.IntrinsicElements["mh-calendar-day-time-view-overlays"] & JSXBase.HTMLAttributes<HTMLMhCalendarDayTimeViewOverlaysElement>;
            "mh-calendar-event": LocalJSX.IntrinsicElements["mh-calendar-event"] & JSXBase.HTMLAttributes<HTMLMhCalendarEventElement>;
            "mh-calendar-event-form": LocalJSX.IntrinsicElements["mh-calendar-event-form"] & JSXBase.HTMLAttributes<HTMLMhCalendarEventFormElement>;
            "mh-calendar-event-full": LocalJSX.IntrinsicElements["mh-calendar-event-full"] & JSXBase.HTMLAttributes<HTMLMhCalendarEventFullElement>;
            /**
             * A day/cell's overflowed events shown in a backdrop-less popover — a header
             * with the date and the full event list. Anchored next to `anchorRect` and
             * dismissible via outside click / Escape.
             * Renders its own popover chrome directly (no separate slotted custom
             * element) so the event list stays reactive: a slot host that doesn't get
             * its own prop changes can fail to re-relocate updated slotted content in
             * non-shadow Stencil components.
             */
            "mh-calendar-event-list-popup": LocalJSX.IntrinsicElements["mh-calendar-event-list-popup"] & JSXBase.HTMLAttributes<HTMLMhCalendarEventListPopupElement>;
            "mh-calendar-event-small": LocalJSX.IntrinsicElements["mh-calendar-event-small"] & JSXBase.HTMLAttributes<HTMLMhCalendarEventSmallElement>;
            "mh-calendar-header": LocalJSX.IntrinsicElements["mh-calendar-header"] & JSXBase.HTMLAttributes<HTMLMhCalendarHeaderElement>;
            "mh-calendar-modal": LocalJSX.IntrinsicElements["mh-calendar-modal"] & JSXBase.HTMLAttributes<HTMLMhCalendarModalElement>;
            "mh-calendar-month": LocalJSX.IntrinsicElements["mh-calendar-month"] & JSXBase.HTMLAttributes<HTMLMhCalendarMonthElement>;
            "mh-calendar-more-events-indicator": LocalJSX.IntrinsicElements["mh-calendar-more-events-indicator"] & JSXBase.HTMLAttributes<HTMLMhCalendarMoreEventsIndicatorElement>;
            "mh-calendar-multi-view": LocalJSX.IntrinsicElements["mh-calendar-multi-view"] & JSXBase.HTMLAttributes<HTMLMhCalendarMultiViewElement>;
            "mh-calendar-navigation": LocalJSX.IntrinsicElements["mh-calendar-navigation"] & JSXBase.HTMLAttributes<HTMLMhCalendarNavigationElement>;
            "mh-calendar-resize-event-handler": LocalJSX.IntrinsicElements["mh-calendar-resize-event-handler"] & JSXBase.HTMLAttributes<HTMLMhCalendarResizeEventHandlerElement>;
            "mh-calendar-resource-view": LocalJSX.IntrinsicElements["mh-calendar-resource-view"] & JSXBase.HTMLAttributes<HTMLMhCalendarResourceViewElement>;
            "mh-calendar-time-slots": LocalJSX.IntrinsicElements["mh-calendar-time-slots"] & JSXBase.HTMLAttributes<HTMLMhCalendarTimeSlotsElement>;
            "mh-view-switcher": LocalJSX.IntrinsicElements["mh-view-switcher"] & JSXBase.HTMLAttributes<HTMLMhViewSwitcherElement>;
        }
    }
}
