/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IMHCalendarEvent as IMHCalendarEvent1, IMHCalendarFullOptions, UserApi } from "./types";
import { IMHCalendarEvent, IMHCalendarViewType } from "./store/mh-calendar-store.types";
import { DragDropState } from "./utils/DragDropHandler";
import { IMHCalendarEvent as IMHCalendarEvent2 } from "./components";
export { IMHCalendarEvent as IMHCalendarEvent1, IMHCalendarFullOptions, UserApi } from "./types";
export { IMHCalendarEvent, IMHCalendarViewType } from "./store/mh-calendar-store.types";
export { DragDropState } from "./utils/DragDropHandler";
export { IMHCalendarEvent as IMHCalendarEvent2 } from "./components";
export namespace Components {
    interface MhCalendar {
        /**
          * @default {}
         */
        "config": IMHCalendarFullOptions;
        /**
          * @default []
         */
        "events": IMHCalendarEvent[];
        "getApi": () => Promise<UserApi>;
        "reactComponent": any;
    }
    interface MhCalendarAgendaView {
    }
    interface MhCalendarDay {
        "day"?: Date;
        /**
          * @default false
         */
        "showCurrentDate": boolean;
    }
    interface MhCalendarDayAllDayEventsHolder {
        "allDayEvents": IMHCalendarEvent1[];
        "dragDropState": DragDropState;
        "handleDragLeave": (e: DragEvent) => void;
        "handleDragOver": (e: DragEvent) => void;
        "handleDrop": (e: DragEvent) => void;
        "showCurrentDate": boolean;
    }
    interface MhCalendarDayDraggedEventPreview {
        "calendarDayElementHeight"?: number;
        "day"?: Date;
        "dragDropState": DragDropState;
        "viewType"?: IMHCalendarViewType;
    }
    interface MhCalendarDayMonthViewEvents {
        "calendarDayElementHeight"?: number;
        "day"?: Date;
        "groupedEvents": IMHCalendarEvent1[];
        "maxVisibleEventsInMonthView": number;
    }
    interface MhCalendarDayTimeViewEvents {
        "calendarDayElementHeight"?: number;
        "day"?: Date;
        "groupedEvents": Map<string, IMHCalendarEvent1[]>;
    }
    interface MhCalendarDayTimeViewOverlays {
        "calendarDayElementHeight": number;
        "currentTimePosition"?: { top: string };
        "day": Date;
        "isTimeView": boolean;
        "isToday": boolean;
    }
    interface MhCalendarEvent {
        "dayHeight"?: number;
        "dayOfRendering"?: Date;
        "event"?: IMHCalendarEvent1;
        "eventTopPosition"?: number;
        "instanceOfEvent"?: string;
        /**
          * @default false
         */
        "isDragged": boolean;
    }
    interface MhCalendarEventFull {
        "event"?: IMHCalendarEvent;
    }
    interface MhCalendarEventSmall {
        "event"?: IMHCalendarEvent2;
    }
    interface MhCalendarHeader {
        /**
          * @default false
         */
        "showCurrentDate": boolean;
    }
    interface MhCalendarModal {
    }
    interface MhCalendarMonth {
    }
    interface MhCalendarMultiView {
    }
    interface MhCalendarNavigation {
        /**
          * @default IMHCalendarViewType.WEEK
         */
        "changeDateRangeByUnit": IMHCalendarViewType;
    }
    interface MhCalendarResizeEventHandler {
        /**
          * @default null
         */
        "dayOfRendering": null | Date;
        "eventColor"?: string;
        /**
          * @default null
         */
        "eventEndDate": null | Date;
        "eventHeight": string;
        "eventId": string;
        /**
          * @default null
         */
        "eventStartDate": null | Date;
    }
    interface MhCalendarShiftplanView {
    }
    interface MhCalendarTimeSlots {
    }
}
declare global {
    interface HTMLMhCalendarElement extends Components.MhCalendar, HTMLStencilElement {
    }
    var HTMLMhCalendarElement: {
        prototype: HTMLMhCalendarElement;
        new (): HTMLMhCalendarElement;
    };
    interface HTMLMhCalendarAgendaViewElement extends Components.MhCalendarAgendaView, HTMLStencilElement {
    }
    var HTMLMhCalendarAgendaViewElement: {
        prototype: HTMLMhCalendarAgendaViewElement;
        new (): HTMLMhCalendarAgendaViewElement;
    };
    interface HTMLMhCalendarDayElement extends Components.MhCalendarDay, HTMLStencilElement {
    }
    var HTMLMhCalendarDayElement: {
        prototype: HTMLMhCalendarDayElement;
        new (): HTMLMhCalendarDayElement;
    };
    interface HTMLMhCalendarDayAllDayEventsHolderElement extends Components.MhCalendarDayAllDayEventsHolder, HTMLStencilElement {
    }
    var HTMLMhCalendarDayAllDayEventsHolderElement: {
        prototype: HTMLMhCalendarDayAllDayEventsHolderElement;
        new (): HTMLMhCalendarDayAllDayEventsHolderElement;
    };
    interface HTMLMhCalendarDayDraggedEventPreviewElement extends Components.MhCalendarDayDraggedEventPreview, HTMLStencilElement {
    }
    var HTMLMhCalendarDayDraggedEventPreviewElement: {
        prototype: HTMLMhCalendarDayDraggedEventPreviewElement;
        new (): HTMLMhCalendarDayDraggedEventPreviewElement;
    };
    interface HTMLMhCalendarDayMonthViewEventsElement extends Components.MhCalendarDayMonthViewEvents, HTMLStencilElement {
    }
    var HTMLMhCalendarDayMonthViewEventsElement: {
        prototype: HTMLMhCalendarDayMonthViewEventsElement;
        new (): HTMLMhCalendarDayMonthViewEventsElement;
    };
    interface HTMLMhCalendarDayTimeViewEventsElement extends Components.MhCalendarDayTimeViewEvents, HTMLStencilElement {
    }
    var HTMLMhCalendarDayTimeViewEventsElement: {
        prototype: HTMLMhCalendarDayTimeViewEventsElement;
        new (): HTMLMhCalendarDayTimeViewEventsElement;
    };
    interface HTMLMhCalendarDayTimeViewOverlaysElement extends Components.MhCalendarDayTimeViewOverlays, HTMLStencilElement {
    }
    var HTMLMhCalendarDayTimeViewOverlaysElement: {
        prototype: HTMLMhCalendarDayTimeViewOverlaysElement;
        new (): HTMLMhCalendarDayTimeViewOverlaysElement;
    };
    interface HTMLMhCalendarEventElement extends Components.MhCalendarEvent, HTMLStencilElement {
    }
    var HTMLMhCalendarEventElement: {
        prototype: HTMLMhCalendarEventElement;
        new (): HTMLMhCalendarEventElement;
    };
    interface HTMLMhCalendarEventFullElement extends Components.MhCalendarEventFull, HTMLStencilElement {
    }
    var HTMLMhCalendarEventFullElement: {
        prototype: HTMLMhCalendarEventFullElement;
        new (): HTMLMhCalendarEventFullElement;
    };
    interface HTMLMhCalendarEventSmallElement extends Components.MhCalendarEventSmall, HTMLStencilElement {
    }
    var HTMLMhCalendarEventSmallElement: {
        prototype: HTMLMhCalendarEventSmallElement;
        new (): HTMLMhCalendarEventSmallElement;
    };
    interface HTMLMhCalendarHeaderElement extends Components.MhCalendarHeader, HTMLStencilElement {
    }
    var HTMLMhCalendarHeaderElement: {
        prototype: HTMLMhCalendarHeaderElement;
        new (): HTMLMhCalendarHeaderElement;
    };
    interface HTMLMhCalendarModalElement extends Components.MhCalendarModal, HTMLStencilElement {
    }
    var HTMLMhCalendarModalElement: {
        prototype: HTMLMhCalendarModalElement;
        new (): HTMLMhCalendarModalElement;
    };
    interface HTMLMhCalendarMonthElement extends Components.MhCalendarMonth, HTMLStencilElement {
    }
    var HTMLMhCalendarMonthElement: {
        prototype: HTMLMhCalendarMonthElement;
        new (): HTMLMhCalendarMonthElement;
    };
    interface HTMLMhCalendarMultiViewElement extends Components.MhCalendarMultiView, HTMLStencilElement {
    }
    var HTMLMhCalendarMultiViewElement: {
        prototype: HTMLMhCalendarMultiViewElement;
        new (): HTMLMhCalendarMultiViewElement;
    };
    interface HTMLMhCalendarNavigationElement extends Components.MhCalendarNavigation, HTMLStencilElement {
    }
    var HTMLMhCalendarNavigationElement: {
        prototype: HTMLMhCalendarNavigationElement;
        new (): HTMLMhCalendarNavigationElement;
    };
    interface HTMLMhCalendarResizeEventHandlerElement extends Components.MhCalendarResizeEventHandler, HTMLStencilElement {
    }
    var HTMLMhCalendarResizeEventHandlerElement: {
        prototype: HTMLMhCalendarResizeEventHandlerElement;
        new (): HTMLMhCalendarResizeEventHandlerElement;
    };
    interface HTMLMhCalendarShiftplanViewElement extends Components.MhCalendarShiftplanView, HTMLStencilElement {
    }
    var HTMLMhCalendarShiftplanViewElement: {
        prototype: HTMLMhCalendarShiftplanViewElement;
        new (): HTMLMhCalendarShiftplanViewElement;
    };
    interface HTMLMhCalendarTimeSlotsElement extends Components.MhCalendarTimeSlots, HTMLStencilElement {
    }
    var HTMLMhCalendarTimeSlotsElement: {
        prototype: HTMLMhCalendarTimeSlotsElement;
        new (): HTMLMhCalendarTimeSlotsElement;
    };
    interface HTMLElementTagNameMap {
        "mh-calendar": HTMLMhCalendarElement;
        "mh-calendar-agenda-view": HTMLMhCalendarAgendaViewElement;
        "mh-calendar-day": HTMLMhCalendarDayElement;
        "mh-calendar-day-all-day-events-holder": HTMLMhCalendarDayAllDayEventsHolderElement;
        "mh-calendar-day-dragged-event-preview": HTMLMhCalendarDayDraggedEventPreviewElement;
        "mh-calendar-day-month-view-events": HTMLMhCalendarDayMonthViewEventsElement;
        "mh-calendar-day-time-view-events": HTMLMhCalendarDayTimeViewEventsElement;
        "mh-calendar-day-time-view-overlays": HTMLMhCalendarDayTimeViewOverlaysElement;
        "mh-calendar-event": HTMLMhCalendarEventElement;
        "mh-calendar-event-full": HTMLMhCalendarEventFullElement;
        "mh-calendar-event-small": HTMLMhCalendarEventSmallElement;
        "mh-calendar-header": HTMLMhCalendarHeaderElement;
        "mh-calendar-modal": HTMLMhCalendarModalElement;
        "mh-calendar-month": HTMLMhCalendarMonthElement;
        "mh-calendar-multi-view": HTMLMhCalendarMultiViewElement;
        "mh-calendar-navigation": HTMLMhCalendarNavigationElement;
        "mh-calendar-resize-event-handler": HTMLMhCalendarResizeEventHandlerElement;
        "mh-calendar-shiftplan-view": HTMLMhCalendarShiftplanViewElement;
        "mh-calendar-time-slots": HTMLMhCalendarTimeSlotsElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface MhCalendar {
        /**
          * @default {}
         */
        "config"?: IMHCalendarFullOptions;
        /**
          * @default []
         */
        "events"?: IMHCalendarEvent[];
        "reactComponent"?: any;
    }
    interface MhCalendarAgendaView {
    }
    interface MhCalendarDay {
        "day"?: Date;
        /**
          * @default false
         */
        "showCurrentDate"?: boolean;
    }
    interface MhCalendarDayAllDayEventsHolder {
        "allDayEvents": IMHCalendarEvent1[];
        "dragDropState": DragDropState;
        "handleDragLeave": (e: DragEvent) => void;
        "handleDragOver": (e: DragEvent) => void;
        "handleDrop": (e: DragEvent) => void;
        "showCurrentDate": boolean;
    }
    interface MhCalendarDayDraggedEventPreview {
        "calendarDayElementHeight"?: number;
        "day"?: Date;
        "dragDropState": DragDropState;
        "viewType"?: IMHCalendarViewType;
    }
    interface MhCalendarDayMonthViewEvents {
        "calendarDayElementHeight"?: number;
        "day"?: Date;
        "groupedEvents": IMHCalendarEvent1[];
        "maxVisibleEventsInMonthView": number;
    }
    interface MhCalendarDayTimeViewEvents {
        "calendarDayElementHeight"?: number;
        "day"?: Date;
        "groupedEvents": Map<string, IMHCalendarEvent1[]>;
    }
    interface MhCalendarDayTimeViewOverlays {
        "calendarDayElementHeight": number;
        "currentTimePosition"?: { top: string };
        "day": Date;
        "isTimeView": boolean;
        "isToday": boolean;
    }
    interface MhCalendarEvent {
        "dayHeight"?: number;
        "dayOfRendering"?: Date;
        "event"?: IMHCalendarEvent1;
        "eventTopPosition"?: number;
        "instanceOfEvent"?: string;
        /**
          * @default false
         */
        "isDragged"?: boolean;
    }
    interface MhCalendarEventFull {
        "event"?: IMHCalendarEvent;
    }
    interface MhCalendarEventSmall {
        "event"?: IMHCalendarEvent2;
    }
    interface MhCalendarHeader {
        /**
          * @default false
         */
        "showCurrentDate"?: boolean;
    }
    interface MhCalendarModal {
    }
    interface MhCalendarMonth {
    }
    interface MhCalendarMultiView {
    }
    interface MhCalendarNavigation {
        /**
          * @default IMHCalendarViewType.WEEK
         */
        "changeDateRangeByUnit"?: IMHCalendarViewType;
    }
    interface MhCalendarResizeEventHandler {
        /**
          * @default null
         */
        "dayOfRendering"?: null | Date;
        "eventColor"?: string;
        /**
          * @default null
         */
        "eventEndDate"?: null | Date;
        "eventHeight": string;
        "eventId": string;
        /**
          * @default null
         */
        "eventStartDate"?: null | Date;
    }
    interface MhCalendarShiftplanView {
    }
    interface MhCalendarTimeSlots {
    }

    interface MhCalendarAttributes {
        "reactComponent": string;
    }
    interface MhCalendarDayAttributes {
        "showCurrentDate": boolean;
    }
    interface MhCalendarDayAllDayEventsHolderAttributes {
        "showCurrentDate": boolean;
    }
    interface MhCalendarDayDraggedEventPreviewAttributes {
        "calendarDayElementHeight": number;
        "viewType": IMHCalendarViewType;
    }
    interface MhCalendarDayMonthViewEventsAttributes {
        "maxVisibleEventsInMonthView": number;
        "calendarDayElementHeight": number;
    }
    interface MhCalendarDayTimeViewEventsAttributes {
        "calendarDayElementHeight": number;
    }
    interface MhCalendarDayTimeViewOverlaysAttributes {
        "calendarDayElementHeight": number;
        "isToday": boolean;
        "isTimeView": boolean;
    }
    interface MhCalendarEventAttributes {
        "dayHeight": number;
        "eventTopPosition": number;
        "isDragged": boolean;
        "instanceOfEvent": string;
    }
    interface MhCalendarHeaderAttributes {
        "showCurrentDate": boolean;
    }
    interface MhCalendarNavigationAttributes {
        "changeDateRangeByUnit": IMHCalendarViewType;
    }
    interface MhCalendarResizeEventHandlerAttributes {
        "eventId": string;
        "eventHeight": string;
        "eventColor": string;
    }

    interface IntrinsicElements {
        "mh-calendar": Omit<MhCalendar, keyof MhCalendarAttributes> & { [K in keyof MhCalendar & keyof MhCalendarAttributes]?: MhCalendar[K] } & { [K in keyof MhCalendar & keyof MhCalendarAttributes as `attr:${K}`]?: MhCalendarAttributes[K] } & { [K in keyof MhCalendar & keyof MhCalendarAttributes as `prop:${K}`]?: MhCalendar[K] };
        "mh-calendar-agenda-view": MhCalendarAgendaView;
        "mh-calendar-day": Omit<MhCalendarDay, keyof MhCalendarDayAttributes> & { [K in keyof MhCalendarDay & keyof MhCalendarDayAttributes]?: MhCalendarDay[K] } & { [K in keyof MhCalendarDay & keyof MhCalendarDayAttributes as `attr:${K}`]?: MhCalendarDayAttributes[K] } & { [K in keyof MhCalendarDay & keyof MhCalendarDayAttributes as `prop:${K}`]?: MhCalendarDay[K] };
        "mh-calendar-day-all-day-events-holder": Omit<MhCalendarDayAllDayEventsHolder, keyof MhCalendarDayAllDayEventsHolderAttributes> & { [K in keyof MhCalendarDayAllDayEventsHolder & keyof MhCalendarDayAllDayEventsHolderAttributes]?: MhCalendarDayAllDayEventsHolder[K] } & { [K in keyof MhCalendarDayAllDayEventsHolder & keyof MhCalendarDayAllDayEventsHolderAttributes as `attr:${K}`]?: MhCalendarDayAllDayEventsHolderAttributes[K] } & { [K in keyof MhCalendarDayAllDayEventsHolder & keyof MhCalendarDayAllDayEventsHolderAttributes as `prop:${K}`]?: MhCalendarDayAllDayEventsHolder[K] } & OneOf<"showCurrentDate", MhCalendarDayAllDayEventsHolder["showCurrentDate"], MhCalendarDayAllDayEventsHolderAttributes["showCurrentDate"]>;
        "mh-calendar-day-dragged-event-preview": Omit<MhCalendarDayDraggedEventPreview, keyof MhCalendarDayDraggedEventPreviewAttributes> & { [K in keyof MhCalendarDayDraggedEventPreview & keyof MhCalendarDayDraggedEventPreviewAttributes]?: MhCalendarDayDraggedEventPreview[K] } & { [K in keyof MhCalendarDayDraggedEventPreview & keyof MhCalendarDayDraggedEventPreviewAttributes as `attr:${K}`]?: MhCalendarDayDraggedEventPreviewAttributes[K] } & { [K in keyof MhCalendarDayDraggedEventPreview & keyof MhCalendarDayDraggedEventPreviewAttributes as `prop:${K}`]?: MhCalendarDayDraggedEventPreview[K] };
        "mh-calendar-day-month-view-events": Omit<MhCalendarDayMonthViewEvents, keyof MhCalendarDayMonthViewEventsAttributes> & { [K in keyof MhCalendarDayMonthViewEvents & keyof MhCalendarDayMonthViewEventsAttributes]?: MhCalendarDayMonthViewEvents[K] } & { [K in keyof MhCalendarDayMonthViewEvents & keyof MhCalendarDayMonthViewEventsAttributes as `attr:${K}`]?: MhCalendarDayMonthViewEventsAttributes[K] } & { [K in keyof MhCalendarDayMonthViewEvents & keyof MhCalendarDayMonthViewEventsAttributes as `prop:${K}`]?: MhCalendarDayMonthViewEvents[K] } & OneOf<"maxVisibleEventsInMonthView", MhCalendarDayMonthViewEvents["maxVisibleEventsInMonthView"], MhCalendarDayMonthViewEventsAttributes["maxVisibleEventsInMonthView"]>;
        "mh-calendar-day-time-view-events": Omit<MhCalendarDayTimeViewEvents, keyof MhCalendarDayTimeViewEventsAttributes> & { [K in keyof MhCalendarDayTimeViewEvents & keyof MhCalendarDayTimeViewEventsAttributes]?: MhCalendarDayTimeViewEvents[K] } & { [K in keyof MhCalendarDayTimeViewEvents & keyof MhCalendarDayTimeViewEventsAttributes as `attr:${K}`]?: MhCalendarDayTimeViewEventsAttributes[K] } & { [K in keyof MhCalendarDayTimeViewEvents & keyof MhCalendarDayTimeViewEventsAttributes as `prop:${K}`]?: MhCalendarDayTimeViewEvents[K] };
        "mh-calendar-day-time-view-overlays": Omit<MhCalendarDayTimeViewOverlays, keyof MhCalendarDayTimeViewOverlaysAttributes> & { [K in keyof MhCalendarDayTimeViewOverlays & keyof MhCalendarDayTimeViewOverlaysAttributes]?: MhCalendarDayTimeViewOverlays[K] } & { [K in keyof MhCalendarDayTimeViewOverlays & keyof MhCalendarDayTimeViewOverlaysAttributes as `attr:${K}`]?: MhCalendarDayTimeViewOverlaysAttributes[K] } & { [K in keyof MhCalendarDayTimeViewOverlays & keyof MhCalendarDayTimeViewOverlaysAttributes as `prop:${K}`]?: MhCalendarDayTimeViewOverlays[K] } & OneOf<"calendarDayElementHeight", MhCalendarDayTimeViewOverlays["calendarDayElementHeight"], MhCalendarDayTimeViewOverlaysAttributes["calendarDayElementHeight"]> & OneOf<"isToday", MhCalendarDayTimeViewOverlays["isToday"], MhCalendarDayTimeViewOverlaysAttributes["isToday"]> & OneOf<"isTimeView", MhCalendarDayTimeViewOverlays["isTimeView"], MhCalendarDayTimeViewOverlaysAttributes["isTimeView"]>;
        "mh-calendar-event": Omit<MhCalendarEvent, keyof MhCalendarEventAttributes> & { [K in keyof MhCalendarEvent & keyof MhCalendarEventAttributes]?: MhCalendarEvent[K] } & { [K in keyof MhCalendarEvent & keyof MhCalendarEventAttributes as `attr:${K}`]?: MhCalendarEventAttributes[K] } & { [K in keyof MhCalendarEvent & keyof MhCalendarEventAttributes as `prop:${K}`]?: MhCalendarEvent[K] };
        "mh-calendar-event-full": MhCalendarEventFull;
        "mh-calendar-event-small": MhCalendarEventSmall;
        "mh-calendar-header": Omit<MhCalendarHeader, keyof MhCalendarHeaderAttributes> & { [K in keyof MhCalendarHeader & keyof MhCalendarHeaderAttributes]?: MhCalendarHeader[K] } & { [K in keyof MhCalendarHeader & keyof MhCalendarHeaderAttributes as `attr:${K}`]?: MhCalendarHeaderAttributes[K] } & { [K in keyof MhCalendarHeader & keyof MhCalendarHeaderAttributes as `prop:${K}`]?: MhCalendarHeader[K] };
        "mh-calendar-modal": MhCalendarModal;
        "mh-calendar-month": MhCalendarMonth;
        "mh-calendar-multi-view": MhCalendarMultiView;
        "mh-calendar-navigation": Omit<MhCalendarNavigation, keyof MhCalendarNavigationAttributes> & { [K in keyof MhCalendarNavigation & keyof MhCalendarNavigationAttributes]?: MhCalendarNavigation[K] } & { [K in keyof MhCalendarNavigation & keyof MhCalendarNavigationAttributes as `attr:${K}`]?: MhCalendarNavigationAttributes[K] } & { [K in keyof MhCalendarNavigation & keyof MhCalendarNavigationAttributes as `prop:${K}`]?: MhCalendarNavigation[K] };
        "mh-calendar-resize-event-handler": Omit<MhCalendarResizeEventHandler, keyof MhCalendarResizeEventHandlerAttributes> & { [K in keyof MhCalendarResizeEventHandler & keyof MhCalendarResizeEventHandlerAttributes]?: MhCalendarResizeEventHandler[K] } & { [K in keyof MhCalendarResizeEventHandler & keyof MhCalendarResizeEventHandlerAttributes as `attr:${K}`]?: MhCalendarResizeEventHandlerAttributes[K] } & { [K in keyof MhCalendarResizeEventHandler & keyof MhCalendarResizeEventHandlerAttributes as `prop:${K}`]?: MhCalendarResizeEventHandler[K] } & OneOf<"eventId", MhCalendarResizeEventHandler["eventId"], MhCalendarResizeEventHandlerAttributes["eventId"]> & OneOf<"eventHeight", MhCalendarResizeEventHandler["eventHeight"], MhCalendarResizeEventHandlerAttributes["eventHeight"]>;
        "mh-calendar-shiftplan-view": MhCalendarShiftplanView;
        "mh-calendar-time-slots": MhCalendarTimeSlots;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mh-calendar": LocalJSX.IntrinsicElements["mh-calendar"] & JSXBase.HTMLAttributes<HTMLMhCalendarElement>;
            "mh-calendar-agenda-view": LocalJSX.IntrinsicElements["mh-calendar-agenda-view"] & JSXBase.HTMLAttributes<HTMLMhCalendarAgendaViewElement>;
            "mh-calendar-day": LocalJSX.IntrinsicElements["mh-calendar-day"] & JSXBase.HTMLAttributes<HTMLMhCalendarDayElement>;
            "mh-calendar-day-all-day-events-holder": LocalJSX.IntrinsicElements["mh-calendar-day-all-day-events-holder"] & JSXBase.HTMLAttributes<HTMLMhCalendarDayAllDayEventsHolderElement>;
            "mh-calendar-day-dragged-event-preview": LocalJSX.IntrinsicElements["mh-calendar-day-dragged-event-preview"] & JSXBase.HTMLAttributes<HTMLMhCalendarDayDraggedEventPreviewElement>;
            "mh-calendar-day-month-view-events": LocalJSX.IntrinsicElements["mh-calendar-day-month-view-events"] & JSXBase.HTMLAttributes<HTMLMhCalendarDayMonthViewEventsElement>;
            "mh-calendar-day-time-view-events": LocalJSX.IntrinsicElements["mh-calendar-day-time-view-events"] & JSXBase.HTMLAttributes<HTMLMhCalendarDayTimeViewEventsElement>;
            "mh-calendar-day-time-view-overlays": LocalJSX.IntrinsicElements["mh-calendar-day-time-view-overlays"] & JSXBase.HTMLAttributes<HTMLMhCalendarDayTimeViewOverlaysElement>;
            "mh-calendar-event": LocalJSX.IntrinsicElements["mh-calendar-event"] & JSXBase.HTMLAttributes<HTMLMhCalendarEventElement>;
            "mh-calendar-event-full": LocalJSX.IntrinsicElements["mh-calendar-event-full"] & JSXBase.HTMLAttributes<HTMLMhCalendarEventFullElement>;
            "mh-calendar-event-small": LocalJSX.IntrinsicElements["mh-calendar-event-small"] & JSXBase.HTMLAttributes<HTMLMhCalendarEventSmallElement>;
            "mh-calendar-header": LocalJSX.IntrinsicElements["mh-calendar-header"] & JSXBase.HTMLAttributes<HTMLMhCalendarHeaderElement>;
            "mh-calendar-modal": LocalJSX.IntrinsicElements["mh-calendar-modal"] & JSXBase.HTMLAttributes<HTMLMhCalendarModalElement>;
            "mh-calendar-month": LocalJSX.IntrinsicElements["mh-calendar-month"] & JSXBase.HTMLAttributes<HTMLMhCalendarMonthElement>;
            "mh-calendar-multi-view": LocalJSX.IntrinsicElements["mh-calendar-multi-view"] & JSXBase.HTMLAttributes<HTMLMhCalendarMultiViewElement>;
            "mh-calendar-navigation": LocalJSX.IntrinsicElements["mh-calendar-navigation"] & JSXBase.HTMLAttributes<HTMLMhCalendarNavigationElement>;
            "mh-calendar-resize-event-handler": LocalJSX.IntrinsicElements["mh-calendar-resize-event-handler"] & JSXBase.HTMLAttributes<HTMLMhCalendarResizeEventHandlerElement>;
            "mh-calendar-shiftplan-view": LocalJSX.IntrinsicElements["mh-calendar-shiftplan-view"] & JSXBase.HTMLAttributes<HTMLMhCalendarShiftplanViewElement>;
            "mh-calendar-time-slots": LocalJSX.IntrinsicElements["mh-calendar-time-slots"] & JSXBase.HTMLAttributes<HTMLMhCalendarTimeSlotsElement>;
        }
    }
}
