export enum ConfigErrorCodes {
  VIRTUAL_SCROLL_1 = 'VIRTUAL_SCROLL_1',
  SHOW_TIME_HOURS = 'SHOW_TIME_HOURS',
  SLOT_TIME_HOURS = 'SLOT_TIME_HOURS',
  SLOT_MINUTES_DIVISIBLE = 'SLOT_MINUTES_DIVISIBLE',
  TIMEZONES_1 = 'TIMEZONES_1',
}
