'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@mhcalendar/calendar/dist/components";
import { MhCalendar as MhCalendarElement, defineCustomElement as defineMhCalendar } from "@mhcalendar/calendar/dist/components/mh-calendar.js";

export type MhCalendarEvents = NonNullable<unknown>;

export const MhCalendar: StencilReactComponent<MhCalendarElement, MhCalendarEvents, Components.MhCalendar> = /*@__PURE__*/ createComponent<MhCalendarElement, MhCalendarEvents, Components.MhCalendar>({
    tagName: 'mh-calendar',
    elementClass: MhCalendarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhCalendarEvents,
    defineCustomElement: defineMhCalendar
});
