'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type MhCalendarPopoverCustomEvent } from "@mhcalendar/calendar";
import type { Components } from "@mhcalendar/calendar/dist/components";
import { MhCalendarEventForm as MhCalendarEventFormElement, defineCustomElement as defineMhCalendarEventForm } from "@mhcalendar/calendar/dist/components/mh-calendar-event-form.js";
import { MhCalendarMoreEventsIndicator as MhCalendarMoreEventsIndicatorElement, defineCustomElement as defineMhCalendarMoreEventsIndicator } from "@mhcalendar/calendar/dist/components/mh-calendar-more-events-indicator.js";
import { MhCalendarPopover as MhCalendarPopoverElement, defineCustomElement as defineMhCalendarPopover } from "@mhcalendar/calendar/dist/components/mh-calendar-popover.js";
import { MhCalendar as MhCalendarElement, defineCustomElement as defineMhCalendar } from "@mhcalendar/calendar/dist/components/mh-calendar.js";
import { MhViewSwitcher as MhViewSwitcherElement, defineCustomElement as defineMhViewSwitcher } from "@mhcalendar/calendar/dist/components/mh-view-switcher.js";

export type MhCalendarEvents = NonNullable<unknown>;

export const MhCalendar: StencilReactComponent<MhCalendarElement, MhCalendarEvents, Components.MhCalendar> = /*@__PURE__*/ createComponent<MhCalendarElement, MhCalendarEvents, Components.MhCalendar>({
    tagName: 'mh-calendar',
    elementClass: MhCalendarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhCalendarEvents,
    defineCustomElement: defineMhCalendar
});

export type MhCalendarEventFormEvents = NonNullable<unknown>;

export const MhCalendarEventForm: StencilReactComponent<MhCalendarEventFormElement, MhCalendarEventFormEvents, Components.MhCalendarEventForm, 'event'> = /*@__PURE__*/ createComponent<MhCalendarEventFormElement, MhCalendarEventFormEvents, Components.MhCalendarEventForm, 'event'>({
    tagName: 'mh-calendar-event-form',
    elementClass: MhCalendarEventFormElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhCalendarEventFormEvents,
    defineCustomElement: defineMhCalendarEventForm
});

export type MhCalendarMoreEventsIndicatorEvents = NonNullable<unknown>;

export const MhCalendarMoreEventsIndicator: StencilReactComponent<MhCalendarMoreEventsIndicatorElement, MhCalendarMoreEventsIndicatorEvents, Components.MhCalendarMoreEventsIndicator, 'hiddenCount'> = /*@__PURE__*/ createComponent<MhCalendarMoreEventsIndicatorElement, MhCalendarMoreEventsIndicatorEvents, Components.MhCalendarMoreEventsIndicator, 'hiddenCount'>({
    tagName: 'mh-calendar-more-events-indicator',
    elementClass: MhCalendarMoreEventsIndicatorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhCalendarMoreEventsIndicatorEvents,
    defineCustomElement: defineMhCalendarMoreEventsIndicator
});

export type MhCalendarPopoverEvents = { onClosePopover: EventName<MhCalendarPopoverCustomEvent<void>> };

export const MhCalendarPopover: StencilReactComponent<MhCalendarPopoverElement, MhCalendarPopoverEvents, Components.MhCalendarPopover, 'anchorRect'> = /*@__PURE__*/ createComponent<MhCalendarPopoverElement, MhCalendarPopoverEvents, Components.MhCalendarPopover, 'anchorRect'>({
    tagName: 'mh-calendar-popover',
    elementClass: MhCalendarPopoverElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onClosePopover: 'closePopover' } as MhCalendarPopoverEvents,
    defineCustomElement: defineMhCalendarPopover
});

export type MhViewSwitcherEvents = NonNullable<unknown>;

export const MhViewSwitcher: StencilReactComponent<MhViewSwitcherElement, MhViewSwitcherEvents, Components.MhViewSwitcher> = /*@__PURE__*/ createComponent<MhViewSwitcherElement, MhViewSwitcherEvents, Components.MhViewSwitcher>({
    tagName: 'mh-view-switcher',
    elementClass: MhViewSwitcherElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhViewSwitcherEvents,
    defineCustomElement: defineMhViewSwitcher
});
