'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@mhcalendar/calendar/dist/components";
import { MhCalendarMoreEventsIndicator as MhCalendarMoreEventsIndicatorElement, defineCustomElement as defineMhCalendarMoreEventsIndicator } from "@mhcalendar/calendar/dist/components/mh-calendar-more-events-indicator.js";
import { MhCalendar as MhCalendarElement, defineCustomElement as defineMhCalendar } from "@mhcalendar/calendar/dist/components/mh-calendar.js";
import { MhViewSwitcher as MhViewSwitcherElement, defineCustomElement as defineMhViewSwitcher } from "@mhcalendar/calendar/dist/components/mh-view-switcher.js";

export type MhCalendarEvents = NonNullable<unknown>;

export const MhCalendar: StencilReactComponent<MhCalendarElement, MhCalendarEvents, Components.MhCalendar> = /*@__PURE__*/ createComponent<MhCalendarElement, MhCalendarEvents, Components.MhCalendar>({
    tagName: 'mh-calendar',
    elementClass: MhCalendarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhCalendarEvents,
    defineCustomElement: defineMhCalendar
});

export type MhCalendarMoreEventsIndicatorEvents = NonNullable<unknown>;

export const MhCalendarMoreEventsIndicator: StencilReactComponent<MhCalendarMoreEventsIndicatorElement, MhCalendarMoreEventsIndicatorEvents, Components.MhCalendarMoreEventsIndicator, 'hiddenCount'> = /*@__PURE__*/ createComponent<MhCalendarMoreEventsIndicatorElement, MhCalendarMoreEventsIndicatorEvents, Components.MhCalendarMoreEventsIndicator, 'hiddenCount'>({
    tagName: 'mh-calendar-more-events-indicator',
    elementClass: MhCalendarMoreEventsIndicatorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhCalendarMoreEventsIndicatorEvents,
    defineCustomElement: defineMhCalendarMoreEventsIndicator
});

export type MhViewSwitcherEvents = NonNullable<unknown>;

export const MhViewSwitcher: StencilReactComponent<MhViewSwitcherElement, MhViewSwitcherEvents, Components.MhViewSwitcher> = /*@__PURE__*/ createComponent<MhViewSwitcherElement, MhViewSwitcherEvents, Components.MhViewSwitcher>({
    tagName: 'mh-view-switcher',
    elementClass: MhViewSwitcherElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhViewSwitcherEvents,
    defineCustomElement: defineMhViewSwitcher
});
