import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';
import { sharedRules } from '../../eslint.config.base.js';

export default [
  {
    // components.ts is auto-generated by the Stencil React Output Target
    ignores: ['dist', 'node_modules', 'src/components/components.ts'],
  },

  js.configs.recommended,

  ...tseslint.configs.recommended,

  {
    files: ['**/*.ts', '**/*.tsx'],

    languageOptions: {
      parser: tseslint.parser,
    },

    rules: sharedRules,
  },

  prettier,
];
